### ISSUE TITLE
Inquire about a question

### ISSUE THREAD

**Issue by Ingram-lin** [probstlukas/gpt3-dementia-detection#1]
Hello, I've been working on replicating your job recently and have encountered some issues. I'd like to ask for assistance.In the Transcription module, after using the Whisper base model for transcription, I have 'train_scraped.csv,' but the generated 'test_scraped.csv' is empty, containing only 'addressfname' and 'transcript.' Is it because the dataset I downloaded only includes training data without testing data, or do I need to manually split it? Or is there another reason?"

**Comment by probstlukas** [comment]
Hello, sorry for my delayed response. I'll gladly assist you with your encountered issue. Which dataset are you using? For this project I used the dataset of the ADReSSo challenge which you can download from [DementiaBank-ADReSS-2021](https://dementia.talkbank.org/ADReSS-2021/). Then you should have both training and test data available and your directory tree should look like this:
<img width="394" alt="Screenshot 2023-10-11 at 12 33 28" src="https://github.com/probstlukas/gpt3-dementia-detection/assets/35579454/244da99b-ddb0-4c9e-9792-ed18a3bd028a">
